import { useCallback } from "react";
import { useLanguage } from "@/hooks/useLanguage";
import type { Translation } from "@/config/translations";

// Admin-only strings live in the lazy admin chunk so they stay out of the
// homepage bundle. Same EN / PT shape as src/config/translations.ts.
const adminStrings = {
  title: { EN: "Content admin", PT: "Administração de conteúdo" },
  intro: {
    EN: "Private area. Sign in with the owner's Google account.",
    PT: "Área privada. Entre com a conta Google do proprietário.",
  },
  signIn: { EN: "Sign in with Google", PT: "Entrar com Google" },
  signOut: { EN: "Sign out", PT: "Sair" },
  loading: { EN: "Checking sign-in…", PT: "Verificando login…" },
  checking: { EN: "Checking access…", PT: "Verificando acesso…" },
  denied: {
    EN: "This account does not have access. It has been signed out.",
    PT: "Esta conta não tem acesso. Ela foi desconectada.",
  },
  error: {
    EN: "Could not verify access. Check your connection and try again.",
    PT: "Não foi possível verificar o acesso. Verifique sua conexão e tente novamente.",
  },
  retry: { EN: "Try again", PT: "Tentar novamente" },
  signInError: {
    EN: "Sign-in failed. Try again.",
    PT: "Falha ao entrar. Tente novamente.",
  },
  unconfigured: {
    EN: "Firebase is not configured for this build. Set the VITE_FIREBASE_* variables.",
    PT: "O Firebase não está configurado nesta build. Defina as variáveis VITE_FIREBASE_*.",
  },
  signedInAs: { EN: "Signed in as", PT: "Conectado como" },
  granted: { EN: "Access confirmed.", PT: "Acesso confirmado." },

  // Dashboard and collections
  "tab.overview": { EN: "Overview", PT: "Visão geral" },
  "tab.files": { EN: "Files", PT: "Arquivos" },
  "tab.settings": { EN: "Settings", PT: "Configurações" },
  "col.experience": { EN: "Experience", PT: "Experiência" },
  "col.education": { EN: "Education", PT: "Formação" },
  "col.projects": { EN: "Projects", PT: "Projetos" },
  "col.projectDetails": { EN: "Project pages", PT: "Páginas de projeto" },
  "col.skills": { EN: "Skills", PT: "Habilidades" },
  "col.about": { EN: "About", PT: "Sobre" },
  overviewIntro: {
    EN: "Published docs appear on the site right away. Page titles, social previews, and the bundled snapshot update on the next deploy.",
    PT: "Documentos publicados aparecem no site na hora. Títulos de página, prévias sociais e o snapshot do build atualizam no próximo deploy.",
  },
  collectionLabel: { EN: "Collection", PT: "Coleção" },
  publishedLabel: { EN: "Published", PT: "Publicados" },
  draftsLabel: { EN: "Drafts", PT: "Rascunhos" },
  loadingContent: { EN: "Loading…", PT: "Carregando…" },
  loadError: { EN: "Could not load content:", PT: "Não foi possível carregar o conteúdo:" },
  reload: { EN: "Reload", PT: "Recarregar" },

  // List actions
  newDoc: { EN: "New", PT: "Novo" },
  edit: { EN: "Edit", PT: "Editar" },
  publish: { EN: "Publish", PT: "Publicar" },
  unpublish: { EN: "Unpublish", PT: "Despublicar" },
  moveUp: { EN: "Move up", PT: "Mover para cima" },
  moveDown: { EN: "Move down", PT: "Mover para baixo" },
  history: { EN: "History", PT: "Histórico" },
  delete: { EN: "Delete", PT: "Excluir" },
  statusPublished: { EN: "Published", PT: "Publicado" },
  statusDraft: { EN: "Draft", PT: "Rascunho" },
  emptyList: { EN: "No docs yet.", PT: "Nenhum documento ainda." },
  saved: { EN: "Saved.", PT: "Salvo." },
  deleted: { EN: "Deleted. It can be restored from history.", PT: "Excluído. Pode ser restaurado pelo histórico." },
  saveError: { EN: "Could not save:", PT: "Não foi possível salvar:" },
  staleError: {
    EN: "This doc changed since it was loaded. Reload and try again.",
    PT: "Este documento mudou desde que foi carregado. Recarregue e tente de novo.",
  },
  publishBlocked: {
    EN: "Fill in the required text in English and Portuguese before publishing.",
    PT: "Preencha o texto obrigatório em inglês e português antes de publicar.",
  },
  confirmDeleteTitle: { EN: "Delete this doc?", PT: "Excluir este documento?" },
  confirmDeleteBody: {
    EN: "It disappears from the site after the next refresh. A copy stays in history.",
    PT: "Ele some do site na próxima atualização. Uma cópia fica no histórico.",
  },
  cancel: { EN: "Cancel", PT: "Cancelar" },
  confirm: { EN: "Confirm", PT: "Confirmar" },

  // Editor
  editorNew: { EN: "New doc", PT: "Novo documento" },
  editorEdit: { EN: "Edit doc", PT: "Editar documento" },
  save: { EN: "Save", PT: "Salvar" },
  saving: { EN: "Saving…", PT: "Salvando…" },
  back: { EN: "Back to list", PT: "Voltar à lista" },
  english: { EN: "English", PT: "Inglês" },
  portuguese: { EN: "Portuguese (Brazil)", PT: "Português (Brasil)" },
  sharedFields: { EN: "Both languages", PT: "Ambos os idiomas" },
  addItem: { EN: "Add item", PT: "Adicionar item" },
  removeItem: { EN: "Remove item", PT: "Remover item" },
  itemLabel: { EN: "Item", PT: "Item" },
  formHasErrors: { EN: "Fix the highlighted fields.", PT: "Corrija os campos destacados." },
  "err.publishBoth": {
    EN: "Required in both languages before publishing.",
    PT: "Obrigatório nos dois idiomas antes de publicar.",
  },
  "err.tooLong": { EN: "Too long.", PT: "Muito longo." },
  "err.format": { EN: "Invalid format.", PT: "Formato inválido." },
  "err.idTaken": { EN: "This id already exists.", PT: "Este id já existe." },
  "err.invalid": { EN: "Invalid value.", PT: "Valor inválido." },

  // Fields
  "field.id": { EN: "Id (lowercase letters, numbers, hyphens)", PT: "Id (letras minúsculas, números, hífens)" },
  "field.published": { EN: "Published", PT: "Publicado" },
  "field.order": { EN: "Order", PT: "Ordem" },
  "field.title": { EN: "Title", PT: "Título" },
  "field.organization": { EN: "Organisation", PT: "Organização" },
  "field.location": { EN: "Location", PT: "Local" },
  "field.period": { EN: "Period", PT: "Período" },
  "field.description": { EN: "Description", PT: "Descrição" },
  "field.bullets": { EN: "Bullets", PT: "Tópicos" },
  "field.imageAlt": { EN: "Image alt text", PT: "Texto alternativo da imagem" },
  "field.image": { EN: "Image", PT: "Imagem" },
  "field.imageWidth": { EN: "Image width (px)", PT: "Largura da imagem (px)" },
  "field.imageHeight": { EN: "Image height (px)", PT: "Altura da imagem (px)" },
  "field.technologies": { EN: "Technologies", PT: "Tecnologias" },
  "field.liveUrl": { EN: "Live URL", PT: "URL ao vivo" },
  "field.githubUrl": { EN: "GitHub URL", PT: "URL do GitHub" },
  "field.detailPath": { EN: "Detail page path", PT: "Caminho da página de detalhe" },
  "field.summary": { EN: "Summary", PT: "Resumo" },
  "field.sections": { EN: "Sections", PT: "Seções" },
  "field.sectionId": { EN: "Section id", PT: "Id da seção" },
  "field.body": { EN: "Body", PT: "Texto" },
  "field.items": { EN: "Items", PT: "Itens" },
  "field.faq": { EN: "FAQ", PT: "Perguntas frequentes" },
  "field.question": { EN: "Question", PT: "Pergunta" },
  "field.answer": { EN: "Answer", PT: "Resposta" },
  "field.storyTitle": { EN: "Story title", PT: "Título da história" },
  "field.storyIntro": { EN: "Story intro", PT: "Introdução da história" },
  "field.story": { EN: "Story", PT: "História" },
  "field.stack": { EN: "Stack", PT: "Tecnologias" },
  "field.label": { EN: "Label", PT: "Rótulo" },
  "field.group": { EN: "Group", PT: "Grupo" },
  "field.iconKey": { EN: "Icon", PT: "Ícone" },
  "field.paragraphs": { EN: "Summary paragraphs", PT: "Parágrafos do resumo" },
  "field.highlights": { EN: "Highlights", PT: "Destaques" },
  "field.fullStory": { EN: "Full story", PT: "História completa" },
  "hint.onePerLine": { EN: "One per line.", PT: "Um por linha." },
  "hint.httpsOrEmpty": { EN: "https:// address, or empty.", PT: "Endereço https://, ou vazio." },
  "hint.detailPath": {
    EN: "For example /projects/big-bang-duel, or empty.",
    PT: "Por exemplo /projects/big-bang-duel, ou vazio.",
  },
  "hint.sectionId": {
    EN: "The page uses try, built, and challenges.",
    PT: "A página usa try, built e challenges.",
  },
  "hint.markdown": {
    EN: "Markdown: # headings, - lists, **bold**, *italic*, > quotes.",
    PT: "Markdown: # títulos, - listas, **negrito**, *itálico*, > citações.",
  },
  "hint.projectDetails": {
    EN: "Only darcy-mcgees and big-bang-duel have pages on the site. Other ids are stored but not shown.",
    PT: "Só darcy-mcgees e big-bang-duel têm páginas no site. Outros ids ficam salvos, mas não aparecem.",
  },
  noneOption: { EN: "None", PT: "Nenhum" },
  "group.programming": { EN: "Programming", PT: "Programação" },
  "group.it": { EN: "IT & infrastructure", PT: "TI e infraestrutura" },
  "group.certification": { EN: "Skills & certifications", PT: "Habilidades e certificações" },
  "group.focus": { EN: "Professional focus", PT: "Foco profissional" },

  // History
  historyTitle: { EN: "History", PT: "Histórico" },
  historyEmpty: { EN: "No earlier versions.", PT: "Nenhuma versão anterior." },
  historyVersion: { EN: "Version", PT: "Versão" },
  restore: { EN: "Restore", PT: "Restaurar" },
  deletedTitle: {
    EN: "Deleted docs (open history to restore)",
    PT: "Documentos excluídos (abra o histórico para restaurar)",
  },
  restored: { EN: "Restored.", PT: "Restaurado." },
  restoreInvalid: {
    EN: "This version no longer matches the content rules and cannot be restored as is.",
    PT: "Esta versão não segue mais as regras de conteúdo e não pode ser restaurada como está.",
  },
  confirmRestoreTitle: { EN: "Restore this version?", PT: "Restaurar esta versão?" },
  confirmRestoreBody: {
    EN: "The current version is saved to history first.",
    PT: "A versão atual é salva no histórico antes.",
  },

  "files.altRequired": {
    EN: "Alt text is required in both languages.",
    PT: "O texto alternativo é obrigatório nos dois idiomas.",
  },
  "crop.title": { EN: "Crop the image", PT: "Recortar a imagem" },
  "crop.description": {
    EN: "Drag the image or use the arrow keys to position it, and use the slider or + and − to zoom. The preview shows exactly what will be uploaded.",
    PT: "Arraste a imagem ou use as setas para posicionar, e use o controle deslizante ou + e − para dar zoom. A prévia mostra exatamente o que será enviado.",
  },
  "crop.previewLabel": { EN: "Crop preview", PT: "Prévia do recorte" },
  "crop.loading": { EN: "Loading the image…", PT: "Carregando a imagem…" },
  "crop.zoom": { EN: "Zoom", PT: "Zoom" },
  "crop.aspect": { EN: "Shape", PT: "Formato" },
  "crop.aspect.square": { EN: "Square (1:1)", PT: "Quadrado (1:1)" },
  "crop.aspect.wide": { EN: "Wide (16:9)", PT: "Panorâmico (16:9)" },
  "crop.aspect.classic": { EN: "Classic (4:3)", PT: "Clássico (4:3)" },
  "crop.aspect.original": { EN: "Original shape", PT: "Formato original" },
  "crop.result": { EN: "Result:", PT: "Resultado:" },
  "crop.reset": { EN: "Reset", PT: "Redefinir" },
  "crop.apply": { EN: "Apply crop", PT: "Aplicar recorte" },
  "upload.preparing": { EN: "Preparing the image…", PT: "Preparando a imagem…" },
  "upload.decode": {
    EN: "The browser can't read this image. Try JPEG, PNG or WebP.",
    PT: "O navegador não consegue ler esta imagem. Tente JPEG, PNG ou WebP.",
  },
  "upload.sourceSize": {
    EN: "Images over 40 MB are too large to compress here. Reduce it first.",
    PT: "Imagens acima de 40 MB são grandes demais para comprimir aqui. Reduza antes.",
  },
  "upload.noFit": {
    EN: "Could not compress the image enough to fit the limit.",
    PT: "Não foi possível comprimir a imagem o bastante para caber no limite.",
  },
  "upload.type": { EN: "This file type is not allowed here.", PT: "Este tipo de arquivo não é permitido aqui." },
  "upload.size": { EN: "The file is larger than the limit.", PT: "O arquivo é maior que o limite." },
  "upload.name": {
    EN: "Set a valid id first (lowercase letters, numbers and hyphens).",
    PT: "Defina um id válido primeiro (letras minúsculas, números e hífens).",
  },
  "upload.auth": { EN: "Your session ended. Sign in again.", PT: "Sua sessão terminou. Entre novamente." },
  "upload.failed": { EN: "Upload failed.", PT: "O envio falhou." },

  // Files and settings screens (admin redesign)
  "files.sub": {
    EN: "The CV download, the hero avatar images and their alt text. Replacing a file never deletes the old one.",
    PT: "O currículo para download, as imagens do avatar e os textos alternativos. Substituir um arquivo nunca apaga o antigo.",
  },
  "files.cv": { EN: "CV", PT: "Currículo" },
  "files.cvLimit": { EN: "PDF · up to {mb} MB", PT: "PDF · até {mb} MB" },
  "files.cvMeta": { EN: "Version {n} · PDF", PT: "Versão {n} · PDF" },
  "files.cvDefault": { EN: "The CV built into the site", PT: "O currículo que já vem no site" },
  "files.openPdf": { EN: "Open PDF", PT: "Abrir PDF" },
  "files.newTab": { EN: "(opens in a new tab)", PT: "(abre em uma nova aba)" },
  "files.replace": { EN: "Replace", PT: "Substituir" },
  "files.crop": { EN: "Crop", PT: "Recortar" },
  "files.resetDefault": { EN: "Reset to default", PT: "Restaurar padrão" },
  "files.resetTitle": { EN: "Reset “{x}” to the default?", PT: "Restaurar “{x}” para o padrão?" },
  "files.resetBody": {
    EN: "The site goes back to the bundled file. The uploaded file stays in storage.",
    PT: "O site volta ao arquivo padrão. O arquivo enviado continua guardado.",
  },
  "files.resetDone": { EN: "Reset to the default file.", PT: "Arquivo padrão restaurado." },
  "files.doneTitle": { EN: "Saved", PT: "Salvo" },
  "files.doneBody": {
    EN: "Visitors get the new file on their next page load.",
    PT: "Os visitantes recebem o novo arquivo no próximo carregamento.",
  },
  "files.pixels": { EN: "{w} × {h} px", PT: "{w} × {h} px" },
  "files.sizeNote": { EN: "{w} × {h} px · {size}.", PT: "{w} × {h} px · {size}." },
  "files.avTitle": { EN: "Avatar images", PT: "Imagens do avatar" },
  "files.avSub": { EN: "The hero card flips between these two faces.", PT: "O card do topo alterna entre estas duas faces." },
  "files.avLimit": { EN: "WebP, AVIF, JPEG or PNG · up to {mb} MB", PT: "WebP, AVIF, JPEG ou PNG · até {mb} MB" },
  "files.photo": { EN: "Photo", PT: "Foto" },
  "files.minifig": { EN: "Minifigure", PT: "Minifigura" },
  "files.bundled": { EN: "Bundled default", PT: "Padrão do site" },
  "files.uploadedV": { EN: "Uploaded · v{n}", PT: "Enviada · v{n}" },
  "files.cropLoadFailed": {
    EN: "Couldn’t load the current image to crop it. Upload a new one instead.",
    PT: "Não foi possível carregar a imagem atual para recortá-la. Envie uma nova.",
  },
  "files.altSave": { EN: "Save alt text", PT: "Salvar texto alternativo" },
  "files.altSaved": { EN: "Alt text saved.", PT: "Texto alternativo salvo." },
  "files.altDefaultHint": {
    EN: "Used with the next upload. The bundled image keeps its built-in text.",
    PT: "Usado no próximo envio. A imagem padrão mantém o texto que já tem.",
  },
  "files.shownFirst": { EN: "Shown first", PT: "Exibida primeiro" },
  "files.firstSaved": { EN: "{x} is now shown first.", PT: "{x} agora aparece primeiro." },
  "files.flipLabel": { EN: "Flip the avatar preview", PT: "Virar a prévia do avatar" },
  "files.flipHint": {
    EN: "Select the avatar to flip it, as visitors do.",
    PT: "Selecione o avatar para virá-lo, como os visitantes fazem.",
  },
  "files.limitsTitle": { EN: "Upload limits", PT: "Limites de envio" },
  "files.limitsSub": {
    EN: "WebP, AVIF, JPEG or PNG for images; PDF for the CV. No SVG or HTML. Images are cropped and re-encoded as WebP before upload.",
    PT: "WebP, AVIF, JPEG ou PNG para imagens; PDF para o currículo. Sem SVG ou HTML. As imagens são recortadas e convertidas para WebP antes do envio.",
  },
  "files.limCv": { EN: "CV (PDF)", PT: "Currículo (PDF)" },
  "files.limProfile": { EN: "Avatar images", PT: "Imagens do avatar" },
  "files.limProject": { EN: "Project images", PT: "Imagens de projeto" },
  "files.limInput": { EN: "Largest image you can pick", PT: "Maior imagem que você pode escolher" },
  "settings.sub": {
    EN: "Site-wide switches. Every change is kept in the settings history.",
    PT: "Chaves que valem para o site todo. Cada mudança fica no histórico de configurações.",
  },
  "settings.remoteTitle": { EN: "Load published content at runtime", PT: "Carregar conteúdo publicado em tempo real" },
  "settings.remoteBody": {
    EN: "On: visitors get your latest published changes shortly after the page loads. Off: the site shows only the content bundled at the last deploy. Turn it off if something published looks wrong and you need the site back to a known state.",
    PT: "Ligado: os visitantes recebem suas últimas alterações publicadas logo depois que a página carrega. Desligado: o site mostra só o conteúdo empacotado no último deploy. Desligue se algo publicado parecer errado e você precisar voltar o site a um estado conhecido.",
  },
  "settings.lastUpdated": { EN: "Last updated {d}", PT: "Atualizado em {d}" },
  "settings.history": { EN: "Settings history", PT: "Histórico de configurações" },
  "settings.offTitle": { EN: "Turn off remote content?", PT: "Desligar o conteúdo remoto?" },
  "settings.offBody": {
    EN: "Visitors see only the content bundled at the last deploy until you turn it back on.",
    PT: "Os visitantes veem só o conteúdo do último deploy até você ligar de novo.",
  },
  "settings.onTitle": { EN: "Turn on remote content?", PT: "Ligar o conteúdo remoto?" },
  "settings.onBody": {
    EN: "Visitors get your latest published changes after the page loads.",
    PT: "Os visitantes recebem suas últimas alterações publicadas depois que a página carrega.",
  },
  "settings.turnOff": { EN: "Turn off", PT: "Desligar" },
  "settings.turnOn": { EN: "Turn on", PT: "Ligar" },
  "settings.remoteToast": { EN: "Remote content is {s}.", PT: "Conteúdo remoto {s}." },
  "settings.restoreTitle": { EN: "Restore settings version {n}?", PT: "Restaurar a versão {n} das configurações?" },
  "settings.restoreBody": {
    EN: "The remote switch and the files go back to this version. The current version is kept in history first.",
    PT: "A chave de conteúdo remoto e os arquivos voltam para esta versão. A versão atual fica no histórico antes.",
  },
  "settings.restored": { EN: "Settings version {n} restored.", PT: "Versão {n} das configurações restaurada." },

  // Shell (admin redesign)
  "shell.admin": { EN: "Admin", PT: "Admin" },
  "shell.content": { EN: "Content", PT: "Conteúdo" },
  "shell.site": { EN: "Site", PT: "Site" },
  "shell.breadcrumb": { EN: "Breadcrumb", PT: "Trilha de navegação" },
  "shell.brandLabel": { EN: "hugoviegas.dev admin, go to the overview", PT: "Admin do hugoviegas.dev, ir para a visão geral" },
  "shell.backToSite": { EN: "Back to site", PT: "Voltar ao site" },
  "shell.preferences": { EN: "Language and theme", PT: "Idioma e tema" },
  "shell.account": { EN: "Account", PT: "Conta" },
  "shell.changeSection": { EN: "Change section", PT: "Mudar de seção" },
  "shell.sections": { EN: "Admin sections", PT: "Seções do admin" },
  "shell.navFoot": {
    EN: "Published changes reach visitors on their next page load. Page titles and social previews update on the next deploy.",
    PT: "Alterações publicadas chegam aos visitantes no próximo carregamento. Títulos de página e prévias sociais atualizam no próximo deploy.",
  },
  "shell.goTo": { EN: "Go to", PT: "Ir para" },
  "shell.close": { EN: "Close", PT: "Fechar" },
  dismiss: { EN: "Dismiss", PT: "Fechar" },
  notFound: { EN: "Page not found", PT: "Página não encontrada" },
  notFoundBody: {
    EN: "This admin address does not exist, or the item was deleted.",
    PT: "Este endereço do admin não existe, ou o item foi excluído.",
  },

  // Sign-in gate
  "gate.unconfiguredTitle": { EN: "The admin isn’t set up for this build", PT: "O admin não está configurado nesta build" },
  "gate.unconfiguredNote": { EN: "Nothing else on the site is affected.", PT: "Nada mais no site é afetado." },
  "gate.deniedTitle": { EN: "This account doesn’t have access", PT: "Esta conta não tem acesso" },
  "gate.otherAccount": { EN: "Sign in with another account", PT: "Entrar com outra conta" },
  "gate.errorTitle": { EN: "Couldn’t check access", PT: "Não foi possível verificar o acesso" },
  "gate.signedInTitle": { EN: "Signed in", PT: "Conectado" },
  "gate.checkingBody": {
    EN: "Checking that this account can open the admin.",
    PT: "Verificando se esta conta pode abrir o admin.",
  },
  "gate.busyBody": { EN: "Finish signing in in the Google window.", PT: "Termine o login na janela do Google." },
  "gate.waiting": { EN: "Waiting for Google…", PT: "Aguardando o Google…" },
  "gate.popupHint": {
    EN: "Didn’t see a window? Allow pop-ups for this site, then try again.",
    PT: "Não viu a janela? Permita pop-ups para este site e tente de novo.",
  },
  "gate.signInHint": {
    EN: "A Google window opens. Only one account has access.",
    PT: "Uma janela do Google se abre. Só uma conta tem acesso.",
  },

  // Unsaved changes
  "unsaved.title": { EN: "Leave without saving?", PT: "Sair sem salvar?" },
  "unsaved.body": {
    EN: "You have unsaved changes to “{x}”. If you leave now, they are lost.",
    PT: "Você tem alterações não salvas em “{x}”. Se sair agora, elas se perdem.",
  },
  "unsaved.thisItem": { EN: "this item", PT: "este item" },
  "unsaved.discard": { EN: "Discard changes", PT: "Descartar alterações" },
  "unsaved.saveLeave": { EN: "Save and leave", PT: "Salvar e sair" },
  "unsaved.keep": { EN: "Keep editing", PT: "Continuar editando" },

  // Overview
  "overview.sub": {
    EN: "What is live on the site, what is still a draft, and the state of your files.",
    PT: "O que está no ar, o que ainda é rascunho e a situação dos seus arquivos.",
  },
  "overview.open": { EN: "Open", PT: "Abrir" },
  "overview.siteSettings": { EN: "Site settings", PT: "Configurações do site" },
  "overview.remote": { EN: "Remote content", PT: "Conteúdo remoto" },
  "overview.on": { EN: "On", PT: "Ligado" },
  "overview.off": { EN: "Off", PT: "Desligado" },
  "overview.lastChange": { EN: "Last content change", PT: "Última alteração de conteúdo" },
  "overview.cv": { EN: "CV", PT: "Currículo" },
  "overview.photo": { EN: "Photo", PT: "Foto" },
  "overview.minifig": { EN: "Minifigure", PT: "Minifigura" },
  "overview.shownFirst": { EN: "Shown first", PT: "Exibida primeiro" },
  "overview.uploaded": { EN: "Uploaded", PT: "Enviada" },
  "overview.bundled": { EN: "Bundled default", PT: "Padrão do site" },
  "overview.openSettings": { EN: "Open settings", PT: "Abrir configurações" },
  "overview.openFiles": { EN: "Open files", PT: "Abrir arquivos" },
  "overview.goOverview": { EN: "Go to the overview", PT: "Ir para a visão geral" },

  // Collection lists
  "lang.en": { EN: "EN", PT: "EN" },
  "lang.pt": { EN: "PT-BR", PT: "PT-BR" },
  "list.sub.experience": { EN: "Roles in the Experience timeline, newest first.", PT: "Cargos da linha do tempo de Experiência, do mais recente ao mais antigo." },
  "list.sub.education": { EN: "Courses in the Education timeline.", PT: "Cursos da linha do tempo de Formação." },
  "list.sub.projects": { EN: "Project cards on the home page, in display order.", PT: "Cards de projeto na página inicial, na ordem de exibição." },
  "list.sub.projectDetails": { EN: "Long-form project pages, matched to a project by id.", PT: "Páginas completas de projeto, ligadas a um projeto pelo id." },
  "list.sub.skills": { EN: "Skill tags, grouped as they appear on the site.", PT: "Tags de habilidades, agrupadas como aparecem no site." },
  "list.sub.about": { EN: "One document: summary, highlights and full story.", PT: "Um documento: resumo, destaques e história completa." },
  "list.new.experience": { EN: "New role", PT: "Nova experiência" },
  "list.new.education": { EN: "New course", PT: "Nova formação" },
  "list.new.projects": { EN: "New project", PT: "Novo projeto" },
  "list.new.projectDetails": { EN: "New project page", PT: "Nova página de projeto" },
  "list.new.skills": { EN: "New skill", PT: "Nova habilidade" },
  "list.new.about": { EN: "New", PT: "Novo" },
  "list.searchLabel": { EN: "Search {x}", PT: "Buscar em {x}" },
  "list.searchPh": { EN: "Search by title or id", PT: "Buscar por título ou id" },
  "list.status": { EN: "Status", PT: "Status" },
  "list.all": { EN: "All", PT: "Todos" },
  "list.showing": { EN: "Showing {a} of {b}", PT: "Mostrando {a} de {b}" },
  "list.count": { EN: "{n} items", PT: "{n} itens" },
  "list.reorderHelp": {
    EN: "Drag a row by its handle to reorder it, or use Move up and Move down. The new order saves straight away.",
    PT: "Arraste uma linha pela alça para reordenar, ou use Mover para cima e Mover para baixo. A nova ordem é salva na hora.",
  },
  "list.dragHint": { EN: "Drag to reorder", PT: "Arraste para reordenar" },
  "list.actionsFor": { EN: "Actions for {x}", PT: "Ações para {x}" },
  "list.aria.edit": { EN: "Edit {x}", PT: "Editar {x}" },
  "list.aria.publish": { EN: "Publish {x}", PT: "Publicar {x}" },
  "list.aria.unpublish": { EN: "Unpublish {x}", PT: "Despublicar {x}" },
  "list.aria.up": { EN: "Move {x} up", PT: "Mover {x} para cima" },
  "list.aria.down": { EN: "Move {x} down", PT: "Mover {x} para baixo" },
  "list.aria.history": { EN: "History of {x}", PT: "Histórico de {x}" },
  "list.aria.delete": { EN: "Delete {x}", PT: "Excluir {x}" },
  "list.aria.more": { EN: "More actions for {x}", PT: "Mais ações para {x}" },
  "list.aria.restore": { EN: "Restore {x}", PT: "Restaurar {x}" },
  "list.loading": { EN: "Loading {x}…", PT: "Carregando {x}…" },
  "list.loadErrorTitle": { EN: "Couldn’t load {x}", PT: "Não foi possível carregar {x}" },
  "list.loadErrorBody": { EN: "Check your connection, then reload. Nothing was changed.", PT: "Verifique sua conexão e recarregue. Nada foi alterado." },
  "list.emptyTitle": { EN: "No {x} yet", PT: "Nenhum item em {x}" },
  "list.emptyBody": {
    EN: "Create the first one. It stays a draft, hidden from the site, until you publish it.",
    PT: "Crie o primeiro. Ele fica como rascunho, oculto do site, até você publicar.",
  },
  "list.noMatch": { EN: "No matches for “{q}”", PT: "Nada encontrado para “{q}”" },
  "list.noMatchBody": { EN: "Try a different word, or clear the search and the status filter.", PT: "Tente outra palavra, ou limpe a busca e o filtro de status." },
  "list.clearSearch": { EN: "Clear search", PT: "Limpar busca" },
  "list.shown": { EN: "Shown on the site", PT: "Exibido no site" },
  "list.notShown": { EN: "Not shown on the public site", PT: "Não aparece no site público" },
  "list.recoveryTitle": { EN: "Recently deleted", PT: "Excluídos recentemente" },
  "list.recoveryHint": { EN: "Kept in history. Restoring brings it back as a draft.", PT: "Guardados no histórico. Restaurar devolve o item como rascunho." },
  "list.recoveryEmpty": { EN: "Nothing deleted here.", PT: "Nada excluído aqui." },
  "list.deletedOn": { EN: "deleted {d}", PT: "excluído em {d}" },
  "list.staleTitle": { EN: "This list changed somewhere else", PT: "Esta lista mudou em outro lugar" },
  "list.writeFailed": { EN: "That change wasn’t saved.", PT: "Essa alteração não foi salva." },
  "list.blockedTitle": { EN: "“{x}” can’t be published yet. Fill in:", PT: "“{x}” ainda não pode ser publicado. Preencha:" },
  "list.openEditor": { EN: "Open the editor", PT: "Abrir o editor" },
  "toast.saved": { EN: "Saved. Visitors see it on their next page load.", PT: "Salvo. Os visitantes veem no próximo carregamento." },
  "toast.published": { EN: "“{x}” is published.", PT: "“{x}” foi publicado." },
  "toast.unpublished": { EN: "“{x}” is now a draft.", PT: "“{x}” agora é rascunho." },
  "toast.order": { EN: "Order saved.", PT: "Ordem salva." },
  "toast.deleted": { EN: "“{x}” deleted. You can restore it from Recently deleted.", PT: "“{x}” excluído. Você pode restaurá-lo em Excluídos recentemente." },
  "toast.restoredDraft": { EN: "“{x}” restored as a draft.", PT: "“{x}” restaurado como rascunho." },
  "dlg.deleteTitle": { EN: "Delete “{x}”?", PT: "Excluir “{x}”?" },
  "dlg.deleteBody": {
    EN: "It leaves the site on the next page load. A copy stays in Recently deleted and in history, so you can restore it.",
    PT: "Ele sai do site no próximo carregamento. Uma cópia fica em Excluídos recentemente e no histórico, então você pode restaurá-lo.",
  },
  "dlg.publishTitle": { EN: "Publish “{x}”?", PT: "Publicar “{x}”?" },
  "dlg.publishBody": { EN: "It appears for visitors on their next page load.", PT: "Ele aparece para os visitantes no próximo carregamento." },
  "dlg.unpublishTitle": { EN: "Unpublish “{x}”?", PT: "Despublicar “{x}”?" },
  "dlg.unpublishBody": { EN: "It is hidden from the site on the next page load. Nothing is deleted.", PT: "Ele fica oculto do site no próximo carregamento. Nada é excluído." },
  "dlg.restoreDeletedTitle": { EN: "Restore “{x}”?", PT: "Restaurar “{x}”?" },
  "dlg.restoreDeletedBody": { EN: "It comes back as a draft. Publish it when you are ready.", PT: "Ele volta como rascunho. Publique quando estiver pronto." },

  // Editor
  "lang.inEnglish": { EN: "English", PT: "inglês" },
  "lang.inPortuguese": { EN: "Portuguese", PT: "português" },
  "err.requiredIn": { EN: "Required in {l} before publishing.", PT: "Obrigatório em {l} antes de publicar." },
  "field.idShort": { EN: "Id", PT: "Id" },
  "hint.group": {
    EN: "The site shows Programming and IT. Skills & certifications and Professional focus are not shown on the public site.",
    PT: "O site mostra Programação e TI. Habilidades e certificações e Foco profissional não aparecem no site público.",
  },
  "editor.newTitle": { EN: "{x}", PT: "{x}" },
  "editor.sub": { EN: "{c} · version {v} · updated {d}", PT: "{c} · versão {v} · atualizado em {d}" },
  "editor.subNew": { EN: "{c} · not saved yet", PT: "{c} · ainda não salvo" },
  "editor.unsaved": { EN: "Unsaved changes", PT: "Alterações não salvas" },
  "editor.saved": { EN: "Saved", PT: "Salvo" },
  "editor.noChanges": { EN: "No unsaved changes", PT: "Nenhuma alteração pendente" },
  "editor.saveFailed": { EN: "Couldn’t save. Check your connection and try again.", PT: "Não foi possível salvar. Verifique a conexão e tente de novo." },
  "editor.saveBar": { EN: "Save changes", PT: "Salvar alterações" },
  "editor.idLocked": { EN: "Set when the item was created. It cannot change.", PT: "Definido na criação do item. Não pode mudar." },
  "editor.idNew": {
    EN: "Lowercase letters, numbers and hyphens. It cannot change after the first save.",
    PT: "Letras minúsculas, números e hífens. Não pode mudar depois do primeiro salvamento.",
  },
  "editor.orderHint": { EN: "Lower numbers come first.", PT: "Números menores aparecem primeiro." },
  "editor.pubOn": { EN: "Published on the site", PT: "Publicado no site" },
  "editor.pubOff": { EN: "Draft · hidden from the site", PT: "Rascunho · oculto do site" },
  "editor.bothLangs": { EN: "Both languages", PT: "Ambos os idiomas" },
  "editor.bothHint": { EN: "The same in English and Portuguese.", PT: "Iguais em inglês e português." },
  "editor.textEach": { EN: "Text in each language", PT: "Texto em cada idioma" },
  "editor.textEachHint": {
    EN: "Fields marked REQUIRED must be filled in both languages before publishing.",
    PT: "Campos marcados como OBRIGATÓRIO precisam estar preenchidos nos dois idiomas antes de publicar.",
  },
  "editor.language": { EN: "Language", PT: "Idioma" },
  "editor.portugueseShort": { EN: "Português (BR)", PT: "Português (BR)" },
  "editor.complete": { EN: "Complete", PT: "Completo" },
  "editor.nMissing": { EN: "{n} missing", PT: "{n} faltando" },
  "editor.required": { EN: "REQUIRED", PT: "OBRIGATÓRIO" },
  "editor.missing": { EN: "Missing", PT: "Falta" },
  "editor.summaryOne": { EN: "Can’t publish yet: 1 required field is empty", PT: "Ainda não dá para publicar: 1 campo obrigatório está vazio" },
  "editor.summaryMany": { EN: "Can’t publish yet: {n} required fields are empty", PT: "Ainda não dá para publicar: {n} campos obrigatórios estão vazios" },
  "editor.summaryBody": {
    EN: "Fill these in, then switch Published on again. Everything else you changed is kept.",
    PT: "Preencha estes campos e ligue Publicado de novo. O resto das suas alterações continua aqui.",
  },
  "editor.items": { EN: "{n} items", PT: "{n} itens" },
  "editor.noItems": { EN: "No items yet.", PT: "Nenhum item ainda." },
  "editor.moveItemUp": { EN: "Move {x} up", PT: "Mover {x} para cima" },
  "editor.moveItemDown": { EN: "Move {x} down", PT: "Mover {x} para baixo" },
  "editor.removeItem": { EN: "Remove {x}", PT: "Remover {x}" },
  "editor.write": { EN: "Write", PT: "Escrever" },
  "editor.preview": { EN: "Preview", PT: "Pré-visualizar" },
  "editor.previewEmpty": { EN: "Nothing to preview yet.", PT: "Nada para pré-visualizar ainda." },
  "editor.changeIcon": { EN: "Change icon", PT: "Trocar ícone" },
  "editor.iconsTitle": { EN: "Choose an icon", PT: "Escolha um ícone" },
  "editor.iconsBody": {
    EN: "Shown next to the skill on the site. None uses the generic code icon.",
    PT: "Aparece ao lado da habilidade no site. Nenhum usa o ícone genérico de código.",
  },
  "item.section": { EN: "Section", PT: "Seção" },
  "item.question": { EN: "Question", PT: "Pergunta" },
  "item.highlight": { EN: "Highlight", PT: "Destaque" },
  "add.section": { EN: "Add section", PT: "Adicionar seção" },
  "add.question": { EN: "Add question", PT: "Adicionar pergunta" },
  "add.highlight": { EN: "Add highlight", PT: "Adicionar destaque" },
  "icon.html": { EN: "HTML5", PT: "HTML5" },
  "icon.css": { EN: "CSS3", PT: "CSS3" },
  "icon.javascript": { EN: "JavaScript", PT: "JavaScript" },
  "icon.php": { EN: "PHP", PT: "PHP" },
  "icon.java": { EN: "Java", PT: "Java" },
  "icon.python": { EN: "Python", PT: "Python" },
  "icon.c": { EN: "C", PT: "C" },
  "icon.vue": { EN: "Vue.js", PT: "Vue.js" },
  "icon.react": { EN: "React", PT: "React" },
  "icon.shell": { EN: "Shell", PT: "Shell" },
  "icon.sql": { EN: "SQL", PT: "SQL" },
  "icon.active-directory": { EN: "Active Directory", PT: "Active Directory" },
  "icon.google-workspace": { EN: "Google Workspace", PT: "Google Workspace" },
  "icon.windows-server": { EN: "Windows Server", PT: "Windows Server" },
  "icon.linux": { EN: "Linux", PT: "Linux" },
  "icon.docker": { EN: "Docker", PT: "Docker" },
  "icon.network": { EN: "Network", PT: "Rede" },

  // Project image
  "image.none": { EN: "No image yet", PT: "Sem imagem ainda" },
  "image.uploaded": { EN: "UPLOADED", PT: "ENVIADA" },
  "image.bundled": { EN: "BUNDLED", PT: "DO SITE" },
  "image.size": { EN: "{w} × {h} px · set from the image", PT: "{w} × {h} px · definido pela imagem" },
  "image.sizeAuto": { EN: "Width and height are set from the image.", PT: "Largura e altura vêm da imagem." },
  "image.upload": { EN: "Upload image", PT: "Enviar imagem" },
  "image.remove": { EN: "Remove", PT: "Remover" },
  "image.limits": {
    EN: "Any image up to 40 MB. It is cropped, then saved as WebP up to {mb} MB.",
    PT: "Qualquer imagem até 40 MB. Ela é recortada e salva como WebP até {mb} MB.",
  },
  "image.steps": { EN: "Upload steps", PT: "Etapas do envio" },
  "image.stepCrop": { EN: "Crop", PT: "Recortar" },
  "image.stepCompress": { EN: "Compress", PT: "Comprimir" },
  "image.stepUpload": { EN: "Upload", PT: "Enviar" },
  "image.stepSave": { EN: "Save project", PT: "Salvar projeto" },
  "image.compressed": { EN: "WebP · {w} × {h} px · {size} (from {from}).", PT: "WebP · {w} × {h} px · {size} (de {from})." },
  "image.uploading": { EN: "Uploading… {p}%", PT: "Enviando… {p}%" },
  "image.doneTitle": { EN: "Image uploaded", PT: "Imagem enviada" },
  "image.doneBody": { EN: "Save the project to use it on the site.", PT: "Salve o projeto para usá-la no site." },
  "image.bundledTitle": { EN: "Bundled images", PT: "Imagens do site" },
  "image.earlier": { EN: "Earlier uploads", PT: "Envios anteriores" },
  "image.earlierItem": { EN: "Earlier upload {n}", PT: "Envio anterior {n}" },
  "image.altEn": { EN: "Alt text · English", PT: "Texto alternativo · inglês" },
  "image.altPt": { EN: "Alt text · Português (Brasil)", PT: "Texto alternativo · português (Brasil)" },
  "image.altHint": {
    EN: "Alt text describes what the image shows, in one short sentence.",
    PT: "O texto alternativo descreve o que a imagem mostra, em uma frase curta.",
  },

  // History
  "history.title": { EN: "History · {x}", PT: "Histórico · {x}" },
  "history.sub": {
    EN: "Every save keeps the previous version. Restoring saves a new version, so nothing is lost.",
    PT: "Cada salvamento guarda a versão anterior. Restaurar salva uma nova versão, então nada se perde.",
  },
  "history.backToEditor": { EN: "Back to editor", PT: "Voltar ao editor" },
  "history.current": { EN: "Current", PT: "Atual" },
  "history.changed": { EN: "Changed:", PT: "Alterado:" },
  "history.failsValidation": { EN: "Fails validation", PT: "Não passa na validação" },
  "history.draftOnly": {
    EN: "This version is missing required text, so it can only come back as a draft.",
    PT: "Esta versão não tem todo o texto obrigatório, então só pode voltar como rascunho.",
  },
  "history.restoreDraft": { EN: "Restore as draft", PT: "Restaurar como rascunho" },
  "history.restoreAria": { EN: "Restore version {n}", PT: "Restaurar a versão {n}" },
  "history.confirmTitle": { EN: "Restore version {n}?", PT: "Restaurar a versão {n}?" },
  "history.asDraftNote": { EN: "It comes back as a draft.", PT: "Ela volta como rascunho." },
} satisfies Record<string, Translation>;

export type AdminStringKey = keyof typeof adminStrings;

export const useAdminT = () => {
  const { language } = useLanguage();
  return useCallback(
    (key: AdminStringKey) => adminStrings[key][language],
    [language],
  );
};

export { adminStrings };
