import { useCallback } from "react";
import { useLanguage } from "@/hooks/useLanguage";
import type { Translation } from "@/config/translations";

// Admin-only strings live in the lazy admin chunk so they stay out of the
// homepage bundle. Same EN / PT shape as src/config/translations.ts.
const adminStrings = {
  title: { EN: "Content admin", PT: "Administração de conteúdo" },
  intro: {
    EN: "Private area. Sign in with the owner's Google account.",
    PT: "Área privada. Entre com a conta Google do proprietário.",
  },
  signIn: { EN: "Sign in with Google", PT: "Entrar com Google" },
  signOut: { EN: "Sign out", PT: "Sair" },
  loading: { EN: "Checking sign-in…", PT: "Verificando login…" },
  checking: { EN: "Checking access…", PT: "Verificando acesso…" },
  denied: {
    EN: "This account does not have access. It has been signed out.",
    PT: "Esta conta não tem acesso. Ela foi desconectada.",
  },
  error: {
    EN: "Could not verify access. Check your connection and try again.",
    PT: "Não foi possível verificar o acesso. Verifique sua conexão e tente novamente.",
  },
  retry: { EN: "Try again", PT: "Tentar novamente" },
  signInError: {
    EN: "Sign-in failed. Try again.",
    PT: "Falha ao entrar. Tente novamente.",
  },
  unconfigured: {
    EN: "Firebase is not configured for this build. Set the VITE_FIREBASE_* variables.",
    PT: "O Firebase não está configurado nesta build. Defina as variáveis VITE_FIREBASE_*.",
  },
  signedInAs: { EN: "Signed in as", PT: "Conectado como" },
  granted: { EN: "Access confirmed.", PT: "Acesso confirmado." },

  // Dashboard and collections
  "tab.overview": { EN: "Overview", PT: "Visão geral" },
  "tab.files": { EN: "Files", PT: "Arquivos" },
  "tab.settings": { EN: "Settings", PT: "Configurações" },
  "col.experience": { EN: "Experience", PT: "Experiência" },
  "col.education": { EN: "Education", PT: "Formação" },
  "col.projects": { EN: "Projects", PT: "Projetos" },
  "col.projectDetails": { EN: "Project pages", PT: "Páginas de projeto" },
  "col.skills": { EN: "Skills", PT: "Habilidades" },
  "col.about": { EN: "About", PT: "Sobre" },
  overviewIntro: {
    EN: "Published docs appear on the site right away. Page titles, social previews, and the bundled snapshot update on the next deploy.",
    PT: "Documentos publicados aparecem no site na hora. Títulos de página, prévias sociais e o snapshot do build atualizam no próximo deploy.",
  },
  collectionLabel: { EN: "Collection", PT: "Coleção" },
  publishedLabel: { EN: "Published", PT: "Publicados" },
  draftsLabel: { EN: "Drafts", PT: "Rascunhos" },
  loadingContent: { EN: "Loading…", PT: "Carregando…" },
  loadError: { EN: "Could not load content:", PT: "Não foi possível carregar o conteúdo:" },
  reload: { EN: "Reload", PT: "Recarregar" },

  // List actions
  newDoc: { EN: "New", PT: "Novo" },
  edit: { EN: "Edit", PT: "Editar" },
  publish: { EN: "Publish", PT: "Publicar" },
  unpublish: { EN: "Unpublish", PT: "Despublicar" },
  moveUp: { EN: "Move up", PT: "Mover para cima" },
  moveDown: { EN: "Move down", PT: "Mover para baixo" },
  history: { EN: "History", PT: "Histórico" },
  delete: { EN: "Delete", PT: "Excluir" },
  statusPublished: { EN: "Published", PT: "Publicado" },
  statusDraft: { EN: "Draft", PT: "Rascunho" },
  emptyList: { EN: "No docs yet.", PT: "Nenhum documento ainda." },
  saved: { EN: "Saved.", PT: "Salvo." },
  deleted: { EN: "Deleted. It can be restored from history.", PT: "Excluído. Pode ser restaurado pelo histórico." },
  saveError: { EN: "Could not save:", PT: "Não foi possível salvar:" },
  staleError: {
    EN: "This doc changed since it was loaded. Reload and try again.",
    PT: "Este documento mudou desde que foi carregado. Recarregue e tente de novo.",
  },
  publishBlocked: {
    EN: "Fill in the required text in English and Portuguese before publishing.",
    PT: "Preencha o texto obrigatório em inglês e português antes de publicar.",
  },
  confirmDeleteTitle: { EN: "Delete this doc?", PT: "Excluir este documento?" },
  confirmDeleteBody: {
    EN: "It disappears from the site after the next refresh. A copy stays in history.",
    PT: "Ele some do site na próxima atualização. Uma cópia fica no histórico.",
  },
  cancel: { EN: "Cancel", PT: "Cancelar" },
  confirm: { EN: "Confirm", PT: "Confirmar" },

  // Editor
  editorNew: { EN: "New doc", PT: "Novo documento" },
  editorEdit: { EN: "Edit doc", PT: "Editar documento" },
  save: { EN: "Save", PT: "Salvar" },
  saving: { EN: "Saving…", PT: "Salvando…" },
  back: { EN: "Back to list", PT: "Voltar à lista" },
  english: { EN: "English", PT: "Inglês" },
  portuguese: { EN: "Portuguese (Brazil)", PT: "Português (Brasil)" },
  sharedFields: { EN: "Both languages", PT: "Ambos os idiomas" },
  addItem: { EN: "Add item", PT: "Adicionar item" },
  removeItem: { EN: "Remove item", PT: "Remover item" },
  itemLabel: { EN: "Item", PT: "Item" },
  formHasErrors: { EN: "Fix the highlighted fields.", PT: "Corrija os campos destacados." },
  "err.publishBoth": {
    EN: "Required in both languages before publishing.",
    PT: "Obrigatório nos dois idiomas antes de publicar.",
  },
  "err.tooLong": { EN: "Too long.", PT: "Muito longo." },
  "err.format": { EN: "Invalid format.", PT: "Formato inválido." },
  "err.idTaken": { EN: "This id already exists.", PT: "Este id já existe." },
  "err.invalid": { EN: "Invalid value.", PT: "Valor inválido." },

  // Fields
  "field.id": { EN: "Id (lowercase letters, numbers, hyphens)", PT: "Id (letras minúsculas, números, hífens)" },
  "field.published": { EN: "Published", PT: "Publicado" },
  "field.order": { EN: "Order", PT: "Ordem" },
  "field.title": { EN: "Title", PT: "Título" },
  "field.organization": { EN: "Organisation", PT: "Organização" },
  "field.location": { EN: "Location", PT: "Local" },
  "field.period": { EN: "Period", PT: "Período" },
  "field.description": { EN: "Description", PT: "Descrição" },
  "field.bullets": { EN: "Bullets", PT: "Tópicos" },
  "field.imageAlt": { EN: "Image alt text", PT: "Texto alternativo da imagem" },
  "field.image": { EN: "Image", PT: "Imagem" },
  "field.imageWidth": { EN: "Image width (px)", PT: "Largura da imagem (px)" },
  "field.imageHeight": { EN: "Image height (px)", PT: "Altura da imagem (px)" },
  "field.technologies": { EN: "Technologies", PT: "Tecnologias" },
  "field.liveUrl": { EN: "Live URL", PT: "URL ao vivo" },
  "field.githubUrl": { EN: "GitHub URL", PT: "URL do GitHub" },
  "field.detailPath": { EN: "Detail page path", PT: "Caminho da página de detalhe" },
  "field.summary": { EN: "Summary", PT: "Resumo" },
  "field.sections": { EN: "Sections", PT: "Seções" },
  "field.sectionId": { EN: "Section id", PT: "Id da seção" },
  "field.body": { EN: "Body", PT: "Texto" },
  "field.items": { EN: "Items", PT: "Itens" },
  "field.faq": { EN: "FAQ", PT: "Perguntas frequentes" },
  "field.question": { EN: "Question", PT: "Pergunta" },
  "field.answer": { EN: "Answer", PT: "Resposta" },
  "field.storyTitle": { EN: "Story title", PT: "Título da história" },
  "field.storyIntro": { EN: "Story intro", PT: "Introdução da história" },
  "field.story": { EN: "Story", PT: "História" },
  "field.stack": { EN: "Stack", PT: "Tecnologias" },
  "field.label": { EN: "Label", PT: "Rótulo" },
  "field.group": { EN: "Group", PT: "Grupo" },
  "field.iconKey": { EN: "Icon", PT: "Ícone" },
  "field.paragraphs": { EN: "Summary paragraphs", PT: "Parágrafos do resumo" },
  "field.highlights": { EN: "Highlights", PT: "Destaques" },
  "field.fullStory": { EN: "Full story", PT: "História completa" },
  "hint.onePerLine": { EN: "One per line.", PT: "Um por linha." },
  "hint.httpsOrEmpty": { EN: "https:// address, or empty.", PT: "Endereço https://, ou vazio." },
  "hint.detailPath": {
    EN: "For example /projects/big-bang-duel, or empty.",
    PT: "Por exemplo /projects/big-bang-duel, ou vazio.",
  },
  "hint.sectionId": {
    EN: "The page uses try, built, and challenges.",
    PT: "A página usa try, built e challenges.",
  },
  "hint.markdown": {
    EN: "Markdown: # headings, - lists, **bold**, *italic*, > quotes.",
    PT: "Markdown: # títulos, - listas, **negrito**, *itálico*, > citações.",
  },
  "hint.projectDetails": {
    EN: "Only darcy-mcgees and big-bang-duel have pages on the site. Other ids are stored but not shown.",
    PT: "Só darcy-mcgees e big-bang-duel têm páginas no site. Outros ids ficam salvos, mas não aparecem.",
  },
  noneOption: { EN: "None", PT: "Nenhum" },
  "group.programming": { EN: "Programming", PT: "Programação" },
  "group.it": { EN: "IT & infrastructure", PT: "TI e infraestrutura" },
  "group.certification": { EN: "Skills & certifications", PT: "Habilidades e certificações" },
  "group.focus": { EN: "Professional focus", PT: "Foco profissional" },

  // History
  historyTitle: { EN: "History", PT: "Histórico" },
  historyEmpty: { EN: "No earlier versions.", PT: "Nenhuma versão anterior." },
  historyVersion: { EN: "Version", PT: "Versão" },
  restore: { EN: "Restore", PT: "Restaurar" },
  deletedTitle: {
    EN: "Deleted docs (open history to restore)",
    PT: "Documentos excluídos (abra o histórico para restaurar)",
  },
  restored: { EN: "Restored.", PT: "Restaurado." },
  restoreInvalid: {
    EN: "This version no longer matches the content rules and cannot be restored as is.",
    PT: "Esta versão não segue mais as regras de conteúdo e não pode ser restaurada como está.",
  },
  confirmRestoreTitle: { EN: "Restore this version?", PT: "Restaurar esta versão?" },
  confirmRestoreBody: {
    EN: "The current version is saved to history first.",
    PT: "A versão atual é salva no histórico antes.",
  },

  // Settings
  useRemoteLabel: {
    EN: "Use Firestore content on the public site",
    PT: "Usar o conteúdo do Firestore no site público",
  },
  useRemoteHint: {
    EN: "Kill switch. When off, the site and the build use the committed snapshot only.",
    PT: "Chave de emergência. Desligada, o site e o build usam só o snapshot do repositório.",
  },
  lastUpdated: { EN: "Last content update:", PT: "Última atualização de conteúdo:" },
  "files.intro": {
    EN: "Files are uploaded to the public Vercel Blob store and appear on the site right after saving. Replacing a file does not delete the old one; remove old files in the Vercel dashboard.",
    PT: "Os arquivos vão para a store pública do Vercel Blob e aparecem no site logo depois de salvar. Substituir um arquivo não apaga o antigo; remova os antigos no painel da Vercel.",
  },
  "files.cvTitle": { EN: "CV (PDF)", PT: "Currículo (PDF)" },
  "files.cvCurrent": { EN: "Open the current CV", PT: "Abrir o currículo atual" },
  "files.cvFallback": {
    EN: "No CV uploaded yet. The site uses the CV link built into the code.",
    PT: "Nenhum currículo enviado ainda. O site usa o link de currículo que está no código.",
  },
  "files.cvFile": { EN: "New CV file", PT: "Novo arquivo do currículo" },
  "files.pdfLimit": { EN: "PDF only, up to", PT: "Somente PDF, até" },
  "files.imageLimit": { EN: "Stored as WebP, AVIF, JPEG or PNG, up to", PT: "Salva como WebP, AVIF, JPEG ou PNG, até" },
  "files.autoCompress": {
    EN: "Any image works: larger files and other formats are compressed automatically, keeping the highest quality that fits.",
    PT: "Qualquer imagem serve: arquivos maiores e outros formatos são comprimidos automaticamente, com a maior qualidade que couber.",
  },
  "files.publicHint": {
    EN: "Anyone with the link can open the file.",
    PT: "Qualquer pessoa com o link pode abrir o arquivo.",
  },
  "files.uploadSave": { EN: "Upload and use", PT: "Enviar e usar" },
  "files.photoTitle": { EN: "Profile photo", PT: "Foto de perfil" },
  "files.photoCurrent": { EN: "Current photo:", PT: "Foto atual:" },
  "files.photoFallback": {
    EN: "No photo uploaded yet. The site uses the photo built into the code.",
    PT: "Nenhuma foto enviada ainda. O site usa a foto que está no código.",
  },
  "files.photoFile": { EN: "New photo file (optional when only editing the alt text)", PT: "Novo arquivo de foto (opcional se for só editar o texto alternativo)" },
  "files.altRequired": {
    EN: "Alt text is required in both languages.",
    PT: "O texto alternativo é obrigatório nos dois idiomas.",
  },
  "files.savePhoto": { EN: "Save photo", PT: "Salvar foto" },
  "files.projectFile": { EN: "Upload a new image", PT: "Enviar uma nova imagem" },
  "files.projectHint": {
    EN: "Width and height are filled in from the file. Save the project to use it.",
    PT: "A largura e a altura são preenchidas a partir do arquivo. Salve o projeto para usá-la.",
  },
  "files.upload": { EN: "Upload", PT: "Enviar" },
  "files.uploadedImage": { EN: "Uploaded image", PT: "Imagem enviada" },
  "upload.chooseFile": { EN: "Choose a file first.", PT: "Escolha um arquivo primeiro." },
  "upload.uploading": { EN: "Uploading…", PT: "Enviando…" },
  "crop.title": { EN: "Crop the image", PT: "Recortar a imagem" },
  "crop.description": {
    EN: "Drag the image or use the arrow keys to position it, and use the slider or + and − to zoom. The preview shows exactly what will be uploaded.",
    PT: "Arraste a imagem ou use as setas para posicionar, e use o controle deslizante ou + e − para dar zoom. A prévia mostra exatamente o que será enviado.",
  },
  "crop.previewLabel": { EN: "Crop preview", PT: "Prévia do recorte" },
  "crop.loading": { EN: "Loading the image…", PT: "Carregando a imagem…" },
  "crop.zoom": { EN: "Zoom", PT: "Zoom" },
  "crop.aspect": { EN: "Shape", PT: "Formato" },
  "crop.aspect.square": { EN: "Square (1:1)", PT: "Quadrado (1:1)" },
  "crop.aspect.wide": { EN: "Wide (16:9)", PT: "Panorâmico (16:9)" },
  "crop.aspect.classic": { EN: "Classic (4:3)", PT: "Clássico (4:3)" },
  "crop.aspect.original": { EN: "Original shape", PT: "Formato original" },
  "crop.result": { EN: "Result:", PT: "Resultado:" },
  "crop.reset": { EN: "Reset", PT: "Redefinir" },
  "crop.apply": { EN: "Apply crop", PT: "Aplicar recorte" },
  "crop.adjust": { EN: "Adjust crop", PT: "Ajustar recorte" },
  "crop.summary": { EN: "Crop:", PT: "Recorte:" },
  "crop.none": { EN: "No crop: the whole image will be used.", PT: "Sem recorte: a imagem inteira será usada." },
  "upload.preparing": { EN: "Preparing the image…", PT: "Preparando a imagem…" },
  "upload.compressedFrom": { EN: "Compressed:", PT: "Comprimida:" },
  "upload.decode": {
    EN: "The browser can't read this image. Try JPEG, PNG or WebP.",
    PT: "O navegador não consegue ler esta imagem. Tente JPEG, PNG ou WebP.",
  },
  "upload.sourceSize": {
    EN: "Images over 40 MB are too large to compress here. Reduce it first.",
    PT: "Imagens acima de 40 MB são grandes demais para comprimir aqui. Reduza antes.",
  },
  "upload.noFit": {
    EN: "Could not compress the image enough to fit the limit.",
    PT: "Não foi possível comprimir a imagem o bastante para caber no limite.",
  },
  "upload.saved": { EN: "Uploaded and saved.", PT: "Enviado e salvo." },
  "upload.readyToSave": {
    EN: "Uploaded. Save the project to use the new image.",
    PT: "Enviado. Salve o projeto para usar a nova imagem.",
  },
  "upload.type": { EN: "This file type is not allowed here.", PT: "Este tipo de arquivo não é permitido aqui." },
  "upload.size": { EN: "The file is larger than the limit.", PT: "O arquivo é maior que o limite." },
  "upload.name": {
    EN: "Set a valid id first (lowercase letters, numbers and hyphens).",
    PT: "Defina um id válido primeiro (letras minúsculas, números e hífens).",
  },
  "upload.auth": { EN: "Your session ended. Sign in again.", PT: "Sua sessão terminou. Entre novamente." },
  "upload.failed": { EN: "Upload failed.", PT: "O envio falhou." },

  // Shell (admin redesign)
  "shell.admin": { EN: "Admin", PT: "Admin" },
  "shell.content": { EN: "Content", PT: "Conteúdo" },
  "shell.site": { EN: "Site", PT: "Site" },
  "shell.breadcrumb": { EN: "Breadcrumb", PT: "Trilha de navegação" },
  "shell.brandLabel": { EN: "hugoviegas.dev admin, go to the overview", PT: "Admin do hugoviegas.dev, ir para a visão geral" },
  "shell.backToSite": { EN: "Back to site", PT: "Voltar ao site" },
  "shell.preferences": { EN: "Language and theme", PT: "Idioma e tema" },
  "shell.account": { EN: "Account", PT: "Conta" },
  "shell.changeSection": { EN: "Change section", PT: "Mudar de seção" },
  "shell.sections": { EN: "Admin sections", PT: "Seções do admin" },
  "shell.navFoot": {
    EN: "Published changes reach visitors on their next page load. Page titles and social previews update on the next deploy.",
    PT: "Alterações publicadas chegam aos visitantes no próximo carregamento. Títulos de página e prévias sociais atualizam no próximo deploy.",
  },
  "shell.goTo": { EN: "Go to", PT: "Ir para" },
  "shell.close": { EN: "Close", PT: "Fechar" },
  dismiss: { EN: "Dismiss", PT: "Fechar" },
  notFound: { EN: "Page not found", PT: "Página não encontrada" },
  notFoundBody: {
    EN: "This admin address does not exist, or the item was deleted.",
    PT: "Este endereço do admin não existe, ou o item foi excluído.",
  },

  // Sign-in gate
  "gate.unconfiguredTitle": { EN: "The admin isn’t set up for this build", PT: "O admin não está configurado nesta build" },
  "gate.unconfiguredNote": { EN: "Nothing else on the site is affected.", PT: "Nada mais no site é afetado." },
  "gate.deniedTitle": { EN: "This account doesn’t have access", PT: "Esta conta não tem acesso" },
  "gate.otherAccount": { EN: "Sign in with another account", PT: "Entrar com outra conta" },
  "gate.errorTitle": { EN: "Couldn’t check access", PT: "Não foi possível verificar o acesso" },
  "gate.signedInTitle": { EN: "Signed in", PT: "Conectado" },
  "gate.checkingBody": {
    EN: "Checking that this account can open the admin.",
    PT: "Verificando se esta conta pode abrir o admin.",
  },
  "gate.busyBody": { EN: "Finish signing in in the Google window.", PT: "Termine o login na janela do Google." },
  "gate.waiting": { EN: "Waiting for Google…", PT: "Aguardando o Google…" },
  "gate.popupHint": {
    EN: "Didn’t see a window? Allow pop-ups for this site, then try again.",
    PT: "Não viu a janela? Permita pop-ups para este site e tente de novo.",
  },
  "gate.signInHint": {
    EN: "A Google window opens. Only one account has access.",
    PT: "Uma janela do Google se abre. Só uma conta tem acesso.",
  },

  // Unsaved changes
  "unsaved.title": { EN: "Leave without saving?", PT: "Sair sem salvar?" },
  "unsaved.body": {
    EN: "You have unsaved changes to “{x}”. If you leave now, they are lost.",
    PT: "Você tem alterações não salvas em “{x}”. Se sair agora, elas se perdem.",
  },
  "unsaved.thisItem": { EN: "this item", PT: "este item" },
  "unsaved.discard": { EN: "Discard changes", PT: "Descartar alterações" },
  "unsaved.saveLeave": { EN: "Save and leave", PT: "Salvar e sair" },
  "unsaved.keep": { EN: "Keep editing", PT: "Continuar editando" },

  // Overview
  "overview.sub": {
    EN: "What is live on the site, what is still a draft, and the state of your files.",
    PT: "O que está no ar, o que ainda é rascunho e a situação dos seus arquivos.",
  },
  "overview.open": { EN: "Open", PT: "Abrir" },
  "overview.siteSettings": { EN: "Site settings", PT: "Configurações do site" },
  "overview.remote": { EN: "Remote content", PT: "Conteúdo remoto" },
  "overview.on": { EN: "On", PT: "Ligado" },
  "overview.off": { EN: "Off", PT: "Desligado" },
  "overview.lastChange": { EN: "Last content change", PT: "Última alteração de conteúdo" },
  "overview.cv": { EN: "CV", PT: "Currículo" },
  "overview.photo": { EN: "Avatar photo", PT: "Foto do avatar" },
  "overview.uploaded": { EN: "Uploaded", PT: "Enviada" },
  "overview.bundled": { EN: "Bundled default", PT: "Padrão do site" },
  "overview.openSettings": { EN: "Open settings", PT: "Abrir configurações" },
  "overview.openFiles": { EN: "Open files", PT: "Abrir arquivos" },
  "overview.goOverview": { EN: "Go to the overview", PT: "Ir para a visão geral" },

  // Collection lists
  "lang.en": { EN: "EN", PT: "EN" },
  "lang.pt": { EN: "PT-BR", PT: "PT-BR" },
  "list.sub.experience": { EN: "Roles in the Experience timeline, newest first.", PT: "Cargos da linha do tempo de Experiência, do mais recente ao mais antigo." },
  "list.sub.education": { EN: "Courses in the Education timeline.", PT: "Cursos da linha do tempo de Formação." },
  "list.sub.projects": { EN: "Project cards on the home page, in display order.", PT: "Cards de projeto na página inicial, na ordem de exibição." },
  "list.sub.projectDetails": { EN: "Long-form project pages, matched to a project by id.", PT: "Páginas completas de projeto, ligadas a um projeto pelo id." },
  "list.sub.skills": { EN: "Skill tags, grouped as they appear on the site.", PT: "Tags de habilidades, agrupadas como aparecem no site." },
  "list.sub.about": { EN: "One document: summary, highlights and full story.", PT: "Um documento: resumo, destaques e história completa." },
  "list.new.experience": { EN: "New role", PT: "Nova experiência" },
  "list.new.education": { EN: "New course", PT: "Nova formação" },
  "list.new.projects": { EN: "New project", PT: "Novo projeto" },
  "list.new.projectDetails": { EN: "New project page", PT: "Nova página de projeto" },
  "list.new.skills": { EN: "New skill", PT: "Nova habilidade" },
  "list.new.about": { EN: "New", PT: "Novo" },
  "list.searchLabel": { EN: "Search {x}", PT: "Buscar em {x}" },
  "list.searchPh": { EN: "Search by title or id", PT: "Buscar por título ou id" },
  "list.status": { EN: "Status", PT: "Status" },
  "list.all": { EN: "All", PT: "Todos" },
  "list.showing": { EN: "Showing {a} of {b}", PT: "Mostrando {a} de {b}" },
  "list.count": { EN: "{n} items", PT: "{n} itens" },
  "list.reorderHelp": {
    EN: "Drag a row by its handle to reorder it, or use Move up and Move down. The new order saves straight away.",
    PT: "Arraste uma linha pela alça para reordenar, ou use Mover para cima e Mover para baixo. A nova ordem é salva na hora.",
  },
  "list.dragHint": { EN: "Drag to reorder", PT: "Arraste para reordenar" },
  "list.actionsFor": { EN: "Actions for {x}", PT: "Ações para {x}" },
  "list.aria.edit": { EN: "Edit {x}", PT: "Editar {x}" },
  "list.aria.publish": { EN: "Publish {x}", PT: "Publicar {x}" },
  "list.aria.unpublish": { EN: "Unpublish {x}", PT: "Despublicar {x}" },
  "list.aria.up": { EN: "Move {x} up", PT: "Mover {x} para cima" },
  "list.aria.down": { EN: "Move {x} down", PT: "Mover {x} para baixo" },
  "list.aria.history": { EN: "History of {x}", PT: "Histórico de {x}" },
  "list.aria.delete": { EN: "Delete {x}", PT: "Excluir {x}" },
  "list.aria.more": { EN: "More actions for {x}", PT: "Mais ações para {x}" },
  "list.aria.restore": { EN: "Restore {x}", PT: "Restaurar {x}" },
  "list.loading": { EN: "Loading {x}…", PT: "Carregando {x}…" },
  "list.loadErrorTitle": { EN: "Couldn’t load {x}", PT: "Não foi possível carregar {x}" },
  "list.loadErrorBody": { EN: "Check your connection, then reload. Nothing was changed.", PT: "Verifique sua conexão e recarregue. Nada foi alterado." },
  "list.emptyTitle": { EN: "No {x} yet", PT: "Nenhum item em {x}" },
  "list.emptyBody": {
    EN: "Create the first one. It stays a draft, hidden from the site, until you publish it.",
    PT: "Crie o primeiro. Ele fica como rascunho, oculto do site, até você publicar.",
  },
  "list.noMatch": { EN: "No matches for “{q}”", PT: "Nada encontrado para “{q}”" },
  "list.noMatchBody": { EN: "Try a different word, or clear the search and the status filter.", PT: "Tente outra palavra, ou limpe a busca e o filtro de status." },
  "list.clearSearch": { EN: "Clear search", PT: "Limpar busca" },
  "list.shown": { EN: "Shown on the site", PT: "Exibido no site" },
  "list.notShown": { EN: "Not shown on the public site", PT: "Não aparece no site público" },
  "list.recoveryTitle": { EN: "Recently deleted", PT: "Excluídos recentemente" },
  "list.recoveryHint": { EN: "Kept in history. Restoring brings it back as a draft.", PT: "Guardados no histórico. Restaurar devolve o item como rascunho." },
  "list.recoveryEmpty": { EN: "Nothing deleted here.", PT: "Nada excluído aqui." },
  "list.deletedOn": { EN: "deleted {d}", PT: "excluído em {d}" },
  "list.staleTitle": { EN: "This list changed somewhere else", PT: "Esta lista mudou em outro lugar" },
  "list.writeFailed": { EN: "That change wasn’t saved.", PT: "Essa alteração não foi salva." },
  "list.blockedTitle": { EN: "“{x}” can’t be published yet. Fill in:", PT: "“{x}” ainda não pode ser publicado. Preencha:" },
  "list.openEditor": { EN: "Open the editor", PT: "Abrir o editor" },
  "toast.saved": { EN: "Saved. Visitors see it on their next page load.", PT: "Salvo. Os visitantes veem no próximo carregamento." },
  "toast.published": { EN: "“{x}” is published.", PT: "“{x}” foi publicado." },
  "toast.unpublished": { EN: "“{x}” is now a draft.", PT: "“{x}” agora é rascunho." },
  "toast.order": { EN: "Order saved.", PT: "Ordem salva." },
  "toast.deleted": { EN: "“{x}” deleted. You can restore it from Recently deleted.", PT: "“{x}” excluído. Você pode restaurá-lo em Excluídos recentemente." },
  "toast.restoredDraft": { EN: "“{x}” restored as a draft.", PT: "“{x}” restaurado como rascunho." },
  "dlg.deleteTitle": { EN: "Delete “{x}”?", PT: "Excluir “{x}”?" },
  "dlg.deleteBody": {
    EN: "It leaves the site on the next page load. A copy stays in Recently deleted and in history, so you can restore it.",
    PT: "Ele sai do site no próximo carregamento. Uma cópia fica em Excluídos recentemente e no histórico, então você pode restaurá-lo.",
  },
  "dlg.publishTitle": { EN: "Publish “{x}”?", PT: "Publicar “{x}”?" },
  "dlg.publishBody": { EN: "It appears for visitors on their next page load.", PT: "Ele aparece para os visitantes no próximo carregamento." },
  "dlg.unpublishTitle": { EN: "Unpublish “{x}”?", PT: "Despublicar “{x}”?" },
  "dlg.unpublishBody": { EN: "It is hidden from the site on the next page load. Nothing is deleted.", PT: "Ele fica oculto do site no próximo carregamento. Nada é excluído." },
  "dlg.restoreDeletedTitle": { EN: "Restore “{x}”?", PT: "Restaurar “{x}”?" },
  "dlg.restoreDeletedBody": { EN: "It comes back as a draft. Publish it when you are ready.", PT: "Ele volta como rascunho. Publique quando estiver pronto." },
} satisfies Record<string, Translation>;

export type AdminStringKey = keyof typeof adminStrings;

export const useAdminT = () => {
  const { language } = useLanguage();
  return useCallback(
    (key: AdminStringKey) => adminStrings[key][language],
    [language],
  );
};

export { adminStrings };
